<?php
/**
 * @package Unlimited Elements
 * @author unlimited-elements.com
 * @copyright (C) 2021 Unlimited Elements, All Rights Reserved.
 * @license GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * */
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * init client text
 */
function ugelInitClientText(){

	
UELM_GlobalsUC::$arrServerSideText = array(
		"uncategorized"=>esc_html__("Uncategorized", "unlimited-elements"),
		"all_addons"=>esc_html__("All Items", "unlimited-elements"),
		"new_layout"=>esc_html__("New Layout", "unlimited-elements"),
		"import_layout"=>esc_html__("Import Layout", "unlimited-elements"),
		"import_layouts"=>esc_html__("Import Layouts", "unlimited-elements"),
		"layouts_global_settings"=>esc_html__("Layouts Global Settings", "unlimited-elements"),
		"save_layout_settings"=>esc_html__("Save Layout Settings", "unlimited-elements"),
		"no_layouts_found"=>esc_html__("No Layouts Found", "unlimited-elements"),
		"layout_title"=>esc_html__("Layout Title", "unlimited-elements"),
		"edit_layout"=>esc_html__("Edit Layout", "unlimited-elements"),
		"back_to_layouts_list"=>esc_html__("Back to layouts list", "unlimited-elements"),
		"my_layouts"=>esc_html__("My Layouts", "unlimited-elements"),
		"layout_deleted"=>esc_html__("Layout Deleted", "unlimited-elements"),
		"layout_duplicated"=>esc_html__("Layout Duplicated", "unlimited-elements"),
		"all_layouts"=>esc_html__("All Layouts", "unlimited-elements"),
		"layouts_added_successfully"=>esc_html__("Layouts Added Successfully", "unlimited-elements"),
		"uploading_layouts_file"=>esc_html__("Uploading Layouts file...", "unlimited-elements"),
		"layout_created"=>esc_html__("Layout Created", "unlimited-elements"),
		"layout_updated"=>esc_html__("Layout Updated", "unlimited-elements"),
		"layout_imported"=>esc_html__("Layout Imported", "unlimited-elements"),
		"layout_saved"=>esc_html__("Layout Saved", "unlimited-elements"),
		"preview_layout"=>esc_html__("Preview Layout", "unlimited-elements"),
		"manage_layout_categories"=>esc_html__("Manage Layout Categories", "unlimited-elements"),
		"set_category_to_layout"=>esc_html__("Set Category To Layout", "unlimited-elements"),
		"select_layouts_export_file"=>esc_html__("Select layouts export file", "unlimited-elements"),
		"are_you_sure_to_delete_this_layout"=>esc_html__("Are you sure to delete this layout?", "unlimited-elements"),
		"addon_library"=>esc_html__("Addon Library", "unlimited-elements"),
		"search_layout"=>esc_html__("Search Layout", "unlimited-elements"),
);


UELM_GlobalsUC::$arrClientSideText = array(
		"empty"=>esc_html__("Empty", "unlimited-elements"),
		"new"=>esc_html__("New", "unlimited-elements"),
		"add_item"=>esc_html__("Add Item","unlimited-elements"),
		"update_item"=>esc_html__("Update Item","unlimited-elements"),
		"edit_item"=>esc_html__("Edit Item","unlimited-elements"),
		"close"=>esc_html__("Close","unlimited-elements"),
		"cancel"=>esc_html__("Cancel","unlimited-elements"),
		"update"=>esc_html__("Update","unlimited-elements"),
		"restore"=>esc_html__("Restore","unlimited-elements"),
		"updating"=>esc_html__("Updating...","unlimited-elements"),
		"restoring"=>esc_html__("Restoring...","unlimited-elements"),
		"import"=>esc_html__("Import","unlimited-elements"),
		"edit"=>esc_html__("Edit","unlimited-elements"),
		"edit_addon"=>esc_html__("Edit Addon","unlimited-elements"),
		"addon_container_settings"=>esc_html__("Addon Container Settings","unlimited-elements"),
		"delete_addon"=>esc_html__("Delete Addon","unlimited-elements"),
		"duplicate_addon"=>esc_html__("Duplicate Addon","unlimited-elements"),
		"updating_categories_order"=>esc_html__("Updating Categories Order...","unlimited-elements"),
		"set_addon"=>esc_html__("Set Addon","unlimited-elements"),
		"add_addon_to_column"=>esc_html__("Add Addon To Column","unlimited-elements"),
		"removing_addons"=>esc_html__("Removing...","unlimited-elements"),
		"updating_addon_title"=>esc_html__("Updating Title...","unlimited-elements"),
		"duplicating_addons"=>esc_html__("Duplicating...","unlimited-elements"),
		"updating_addons_order"=>esc_html__("Updating Order...","unlimited-elements"),
		"updating_addons"=>esc_html__("Updating...","unlimited-elements"),
		"copying_addons"=>esc_html__("Copying...","unlimited-elements"),
		"moving_addons"=>esc_html__("Moving...","unlimited-elements"),
		"confirm_remove_addons"=>esc_html__("Are you sure you want to delete these addons?","unlimited-elements"),
		"uc_listing"=>esc_html__("Grouped Settings","unlimited-elements"),
		"uc_textfield"=>esc_html__("Text Field","unlimited-elements"),
		"uc_textarea"=>esc_html__("Text Area","unlimited-elements"),
		"uc_checkbox"=>esc_html__("Checkbox","unlimited-elements"),
		"uc_dropdown"=>esc_html__("Dropdown","unlimited-elements"),
		"uc_multiple_select"=>esc_html__("Multiple Select","unlimited-elements"),
		"uc_radioboolean"=>esc_html__("Radio Boolean","unlimited-elements"),
		"uc_special"=>esc_html__("Special Attribute","unlimited-elements"),
		"uc_typography"=>esc_html__("Typography","unlimited-elements"),
		"uc_link"=>esc_html__("Link","unlimited-elements"),
		"uc_number"=>esc_html__("Number","unlimited-elements"),
		"uc_colorpicker"=>esc_html__("Color Picker","unlimited-elements"),
		"uc_editor"=>esc_html__("Editor","unlimited-elements"),
		"uc_icon"=>esc_html__("Icon Picker","unlimited-elements"),
		"uc_icon_library"=>esc_html__("Icon Library","unlimited-elements"),
		"uc_shape"=>esc_html__("Shape Picker","unlimited-elements"),
		"uc_addonpicker"=>esc_html__("Addon Picker","unlimited-elements"),
		"uc_map"=>esc_html__("Google Map Picker","unlimited-elements"),
		"uc_image"=>esc_html__("Image","unlimited-elements"),
		"uc_file"=>esc_html__("File","unlimited-elements"),
		"uc_mp3"=>esc_html__("Audio","unlimited-elements"),
		"uc_post"=>esc_html__("Post","unlimited-elements"),
		"uc_posts_list"=>esc_html__("Posts List","unlimited-elements"),
		"uc_padding"=>esc_html__("Padding","unlimited-elements"),
		"uc_margins"=>esc_html__("Margin","unlimited-elements"),
		"uc_post_terms"=>esc_html__("Post Terms","unlimited-elements"),
		"uc_users"=>esc_html__("Users List","unlimited-elements"),
		"uc_template"=>esc_html__("Elementor Template","unlimited-elements"),
		"uc_font_override"=>esc_html__("Font Override","unlimited-elements"),
		"uc_imagebase"=>esc_html__("Image Fields","unlimited-elements"),
		"uc_menu"=>esc_html__("Menu","unlimited-elements"),
		"uc_hr"=>esc_html__("HR Line","unlimited-elements"),

		"uc_slider"=>esc_html__("Slider","unlimited-elements"),
		"uc_background"=>esc_html__("Backgound","unlimited-elements"),
		"uc_border"=>esc_html__("Border","unlimited-elements"),
		"uc_datetime"=>esc_html__("Date Time","unlimited-elements"),
		"uc_instagram"=>esc_html__("Instagram","unlimited-elements"),
		"uc_textshadow"=>esc_html__("Text Shadow","unlimited-elements"),
		"uc_textstroke"=>esc_html__("Text Stroke","unlimited-elements"),
		"uc_boxshadow"=>esc_html__("Box Shadow","unlimited-elements"),
		"uc_border_dimentions"=>esc_html__("Border Radius","unlimited-elements"),
		"uc_css_filters"=>esc_html__("Css Filters","unlimited-elements"),
		"uc_hover_animations"=>esc_html__("Hover Animations","unlimited-elements"),

		"choose_icon"=>esc_html__("Choose Icon","unlimited-elements"),
		"choose_image"=>esc_html__("Choose Image","unlimited-elements"),
		"choose_images"=>esc_html__("Choose Images","unlimited-elements"),
		"choose_audio"=>esc_html__("Choose Audio","unlimited-elements"),
		"edit_file"=>esc_html__("Edit File","unlimited-elements"),
		"save"=>esc_html__("Save","unlimited-elements"),
		"delete_op"=>esc_html__("Delete","unlimited-elements"),
		"duplicate_op"=>esc_html__("Duplicate","unlimited-elements"),
		"bulk"=>esc_html__("Bulk","unlimited-elements"),
		"delete_include"=>esc_html__("Delete Include","unlimited-elements"),
		"add_include"=>esc_html__("Add Include","unlimited-elements"),
		"include_settings"=>esc_html__("Include Settings","unlimited-elements"),
		"always"=>esc_html__("Always","unlimited-elements"),
		"never_include"=>esc_html__("Never Include","unlimited-elements"),
		"not_selected"=>esc_html__("Not Selected","unlimited-elements"),
		"choose_addon"=>esc_html__("Choose Addon","unlimited-elements"),

		"delete_row"=>esc_html__("Delete Row","unlimited-elements"),
		"duplicate_row"=>esc_html__("Duplicate Row","unlimited-elements"),
		"copy_row"=>esc_html__("Copy Row","unlimited-elements"),
		"delete_section"=>esc_html__("Delete Section","unlimited-elements"),
		"duplicate_section"=>esc_html__("Duplicate Section","unlimited-elements"),
		"copy_section"=>esc_html__("Copy Section","unlimited-elements"),
		"paste_section"=>esc_html__("Paste Section","unlimited-elements"),
		"save_to_library"=>esc_html__("Save To Library","unlimited-elements"),
		"in_buffer"=>esc_html__("In Buffer","unlimited-elements"),
		"delete_column"=>esc_html__("Delete Column","unlimited-elements"),
		"duplicate_column"=>esc_html__("Duplicate Column","unlimited-elements"),
		"column_settings"=>esc_html__("Column Settings","unlimited-elements"),
		"add_column"=>esc_html__("Add Column","unlimited-elements"),
		"move_row"=>esc_html__("Move Row","unlimited-elements"),
		"move_section"=>esc_html__("Move Section","unlimited-elements"),
		"move_column"=>esc_html__("Move Column","unlimited-elements"),
		"move_addon"=>esc_html__("Move Addon","unlimited-elements"),
		"settings"=>esc_html__("Settings","unlimited-elements"),
		"row"=>esc_html__("Row","unlimited-elements"),
		"section"=>esc_html__("Section","unlimited-elements"),
		"row_layout"=>esc_html__("Row Layout", "unlimited-elements"),
		"more_actions"=>esc_html__("More Actions", "unlimited-elements"),
		"less_actions"=>esc_html__("Less Actions", "unlimited-elements"),
		"hidden_row"=>esc_html__("Hidden Row", "unlimited-elements"),
		"hidden_column"=>esc_html__("Hidden Column", "unlimited-elements"),
		"hidden_addon"=>esc_html__("Hidden Addon", "unlimited-elements"),
		"section_anchor"=>esc_html__("Section Anchor", "unlimited-elements"),
		"edit_section"=>esc_html__("Edit Section", "unlimited-elements"),
		"copy_section"=>esc_html__("Copy Section", "unlimited-elements"),
		"delete_section"=>esc_html__("Delete Section", "unlimited-elements"),
		"delete_section_error"=>esc_html("This section is not empty.\\nYou can delete only empty sections.","unlimited-elements"),
		"delete_default_section_error"=>esc_html__("You can not delete this section.","unlimited-elements"),
		"empty_text"=>esc_html__("Empty Text","unlimited-elements"),
		"display_condition"=>esc_html__("Display Condition","unlimited-elements"),

		"prohibition_setting_attribute_deletion"=>esc_html__("This setting contains Pro options, and can't be deleted.","unlimited-elements"),
		"prohibition_setting_attribute_duplication"=>esc_html__("This setting contains Pro options, and can't be duplicated.","unlimited-elements"),
		"prohibition_section_attribute_copied"=>esc_html__("This section contains Pro options, and can't be copied.","unlimited-elements")
);

$filepathProviderClientText = UELM_GlobalsUC::$pathProvider."provider_client_text.php";

if(file_exists($filepathProviderClientText))
	require $filepathProviderClientText;
	
}